### ISSUE TITLE
Unexpected http status in response: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by juanbar** [rschreijer/lutung#35]
Hi,
I'm having some problems while trying to get info from subaccounts. The error is: 

Unexpected http status in response: 500 (Internal Server Error)

Seems to happen when the subaccount does not exists

MandrillSubaccountInfo mandrillSubaccountInfo = mandrillApi.subaccounts().info(subaccountId);

subaccountId is 658

Also, when I try to send an email, and the subaccount doesn't exists, the error message shows:

{
  "status": "error",
  "name": "Unknown_Subaccount",
  "message": "No subaccount exists with the id \u0027658\u0027",
  "code": 12
}

**Comment by CliqLabs** [comment]
Based on the error message, it appears that you're adding extraneous apostrophe characters when calling the info() method.  "\u0027" is the Unicode character for an apostrophe.  In other words, you appear to be using "'658'" (the string 658 surrounded by apostrophe characters) instead of just "658".  See the difference?  Clean up your input and try again.
